# Node.js Dockerfile
FROM node:18-slim

# Set the working directory inside the container
WORKDIR /github/workspace

# Copy the entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Run the entrypoint script when the container starts
ENTRYPOINT ["/entrypoint.sh"]
